services:
  app:
    build: .
    working_dir: /var/www
    volumes:
      - .:/var/www:z
    environment:
      - MIKROTIK_TIMEOUT=${MIKROTIK_TIMEOUT}
      - APP_URL=${APP_URL}
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - DB_PATH=${DB_PATH}
    ports:
      - "1300:80"
